import '../model_info.dart';

const List<CloudModelInfo> kGeminiModels = [
  CloudModelInfo(
    modelName: 'gemini-3.7-flash',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 5,
    limitTpm: 250000,
    limitRpd: 20,
    inputPricePerMillion: 1.50,
    outputPricePerMillion: 7.50,
    description: 'Free Tier Limits: 5 RPM / 250k TPM / 20 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemini-3.6-flash',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 5,
    limitTpm: 250000,
    limitRpd: 20,
    inputPricePerMillion: 1.50,
    outputPricePerMillion: 7.50,
    description: 'Free Tier Limits: 5 RPM / 250k TPM / 20 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemini-3.5-flash',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 5,
    limitTpm: 250000,
    limitRpd: 20,
    inputPricePerMillion: 1.50,
    outputPricePerMillion: 9.00,
    description: 'Free Tier Limits: 5 RPM / 250k TPM / 20 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemini-3.5-flash-lite',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 15,
    limitTpm: 250000,
    limitRpd: 500,
    inputPricePerMillion: 0.75,
    outputPricePerMillion: 3.00,
    description: 'Free Tier Limits: 15 RPM / 250k TPM / 500 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemini-3.1-pro',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: null,
    limitTpm: null,
    limitRpd: null,
    inputPricePerMillion: 2.00,
    outputPricePerMillion: 12.00,
    description: 'Paid Tier Only (No free tier)',
  ),
  CloudModelInfo(
    modelName: 'gemini-3-flash',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 5,
    limitTpm: 250000,
    limitRpd: 20,
    inputPricePerMillion: 1.50,
    outputPricePerMillion: 9.00,
    description: 'Free Tier Limits: 5 RPM / 250k TPM / 20 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemini-3.1-flash-lite',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 15,
    limitTpm: 250000,
    limitRpd: 500,
    inputPricePerMillion: 0.25,
    outputPricePerMillion: 1.50,
    description: 'Free Tier Limits: 15 RPM / 250k TPM / 500 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemma-4-31b-it',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 15,
    limitTpm: 250000,
    limitRpd: 1500,
    inputPricePerMillion: 0.0,
    outputPricePerMillion: 0.0,
    description: 'Free Tier Limits: 15 RPM / 250k TPM / 1,500 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemma-4-26b-it',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 15,
    limitTpm: 250000,
    limitRpd: 1500,
    inputPricePerMillion: 0.0,
    outputPricePerMillion: 0.0,
    description: 'Free Tier Limits: 15 RPM / 250k TPM / 1,500 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemma-4-12b-it',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 15,
    limitTpm: 250000,
    limitRpd: 1500,
    inputPricePerMillion: 0.0,
    outputPricePerMillion: 0.0,
    description: 'Free Tier Limits: 15 RPM / 250k TPM / 1,500 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemma-4-4b-it',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 15,
    limitTpm: 250000,
    limitRpd: 1500,
    inputPricePerMillion: 0.0,
    outputPricePerMillion: 0.0,
    description: 'Free Tier Limits: 15 RPM / 250k TPM / 1,500 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemma-4-2b-it',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 15,
    limitTpm: 250000,
    limitRpd: 1500,
    inputPricePerMillion: 0.0,
    outputPricePerMillion: 0.0,
    description: 'Free Tier Limits: 15 RPM / 250k TPM / 1,500 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemini-2.5-pro',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 2,
    limitTpm: 32000,
    limitRpd: 50,
    inputPricePerMillion: 1.25,
    outputPricePerMillion: 10.00,
    description: 'Free Tier Limits: 2 RPM / 32k TPM / 50 RPD',
  ),
  CloudModelInfo(
    modelName: 'gemini-2.5-flash',
    provider: CloudProvider.gemini,
    isVision: true,
    limitRpm: 15,
    limitTpm: 1000000,
    limitRpd: 1500,
    inputPricePerMillion: 0.30,
    outputPricePerMillion: 2.50,
    description: 'Free Tier Limits: 15 RPM / 1M TPM / 1,500 RPD',
  ),
];
